### PR TITLE
Align f4-uart branch with master 0.13

### PR DESCRIPTION
**Pull request by rmja**
This PR aligns the f4-uart branch with the 0.13 version in master that was just released.

### CODE REVIEW

**Comment by rmja** [comment]
cc @alfredch

**Review by alfredch — APPROVED** [review]
Thank you! I will wait to merge this branch into master until we have an example app with uart (and hopefully also a USB device, which is quite demanding.)

**Comment by rmja** [comment]
@alfredch I am working on a uart app, and will let you know of anything that I see on the way.

**Comment by alfredch** [comment]
@rmja We appreciate your contributions!

**Pull request merged**
